resolver: lts-18.27
compiler: ghc-8.10.7
packages:
    - .
extra-deps:
    - location:
      git: https://github.com/ucsd-progsys/liquidhaskell
      commit: fc842d2448d9e63b0ec194920600c3931c10ba9c
    - location: 
      git: https://github.com/liquidhaskell/liquid-base
      commit: 79e2bee57ef6e34e69a80cd361bc8edde80da34a 
    - location: 
      git: https://github.com/liquidhaskell/liquid-containers
      commit: 845942a8fdca5ab785c2e0e5202e5beaf94bc327 
    - liquid-ghc-prim-0.6.1
    - location: 
      git: https://github.com/ucsd-progsys/liquid-fixpoint
      commit: a63a20e8e73f2a3c214a874cc6b2da0f76a57318
    - rest-rewrite-0.3.0
    - liquid-prelude-0.8.10.2

    
allow-newer: true
